# Generated by Django 5.2.6 on 2026-09-21 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('image', models.URLField(blank=True)),
                ('bio', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('content_type', models.CharField(choices=[('movie', 'Movie'), ('show', 'TV Show'), ('anime', 'Anime'), ('live', 'Live')], max_length=20)),
                ('description', models.TextField()),
                ('poster', models.URLField(blank=True)),
                ('backdrop', models.URLField(blank=True)),
                ('trailer', models.URLField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=50)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('language', models.CharField(blank=True, max_length=80)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('quality', models.CharField(default='HD', max_length=30)),
                ('director', models.CharField(blank=True, max_length=160)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('views', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genres', models.ManyToManyField(blank=True, related_name='contents', to='catalog.genre')),
                ('cast', models.ManyToManyField(blank=True, related_name='acted_contents', to='catalog.person')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=80)),
                ('viewers', models.PositiveIntegerField(default=0)),
                ('start_time', models.DateTimeField()),
                ('is_live', models.BooleanField(default=False)),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_event', to='catalog.content')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='catalog.content')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('content', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.URLField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('duration', models.CharField(blank=True, max_length=50)),
                ('air_date', models.DateField(blank=True, null=True)),
                ('views', models.PositiveBigIntegerField(default=0)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='catalog.season')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('season', 'number')},
            },
        ),
    ]
